name: deployment


on:
  push:
    branches:
      - main
jobs:
  checkout:
    name: checkout
    uses: actions/checkout@v4
    with:
        repository: ''
        token: ${{ secrets.GH_TOKEN }}

  build:
    name: build image
    runs-on:  ubuntu-latest
    steps:
      - name: build
        run: |
           echo "Logging in to Docker Hub..."
           docker login -u ${{ secrets.DOCKER_LOGIN }} --password-stdin << EOF
           ${{ secrets.DOCKER_PASSWORD }}
           EOF
           docker build . -t docker.io/chabir/resume:latest
           docker push  docker.io/chabir/resume:latest 
  deploy:
    name: deploy to server
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: install ssh key
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }}
      - name: deploy
        run: |
           ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << 'EOF'
            docker login -u ${{ secrets.DOCKER_LOGIN }} --password-stdin << EOF
           ${{ secrets.DOCKER_PASSWORD }}
           EOF
           docker pull docker.io/chabir/resume:latest
           docker stop resume || true
           docker rm resume || true
           sudo docker run -d --name resume -p 80:80 -p 443:443 -v /home/ubuntu/CV/certs:/etc/nginx/certs/ -v /home/ubuntu/CV/nginx-conf:/etc/nginx/conf.d/ docker.io/chabir/resume:latest
