name: deployment

on:
  push:
    branches:
      - main

jobs:
  checkout:
    name: checkout
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

  build:
    name: build image
    runs-on: ubuntu-latest
    needs: checkout
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_LOGIN }}" --password-stdin

      - name: Build and Push Docker Image
        run: |
          docker build . -t docker.io/chabir/resume:latest
          docker push docker.io/chabir/resume:latest

  deploy:
    name: deploy to server
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Install SSH key
        run: |
          echo "${{ secrets.SSH_KEY }}" > /tmp/ssh_key
          chmod 600 /tmp/ssh_key
          eval "$(ssh-agent -s)"
          ssh-add /tmp/ssh_key          

      - name: Deploy to server
        run: |
          ssh -i /tmp/ssh_key -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << 'EOF'
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_LOGIN }}" --password-stdin
          docker pull docker.io/chabir/resume:latest
          docker stop resume || true
          docker rm resume || true
          docker run -d --name resume -p 80:80 -p 443:443 \
            -v /home/ubuntu/CV/certs/cv.chabir.com/fullchain.pem:/etc/nginx/certs/cv.chabir.com/fullchain.pem\
            -v /home/ubuntu/CV/certs/cv.chabir.com/privkey.pem:/etc/nginx/certs/cv.chabir.com/privkey.pem \
            -v /home/ubuntu/CV/nginx-conf:/etc/nginx/conf.d/ \
            docker.io/chabir/resume:latest
          EOF
